package repository

const (
	dossierTable                = `CREATE TABLE IF NOT EXISTS dossiers (dossier_id TEXT PRIMARY KEY, revision INTEGER NOT NULL, status TEXT NOT NULL, subject_code TEXT NOT NULL DEFAULT '', editor_id TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '', payload BLOB NOT NULL)`
	idempotencyTable            = `CREATE TABLE IF NOT EXISTS idempotency (request_id TEXT PRIMARY KEY, fingerprint TEXT NOT NULL, status INTEGER NOT NULL, response BLOB NOT NULL)`
	dossierIndex                = `CREATE INDEX IF NOT EXISTS dossiers_status_idx ON dossiers(status)`
	dossierQueueIndex           = `CREATE INDEX IF NOT EXISTS dossiers_queue_idx ON dossiers(updated_at DESC,dossier_id ASC)`
	segmentsTable               = `CREATE TABLE IF NOT EXISTS transcript_segments (dossier_id TEXT NOT NULL, segment_id TEXT NOT NULL, sequence INTEGER NOT NULL, start_ms INTEGER NOT NULL, end_ms INTEGER NOT NULL, speaker_code TEXT NOT NULL, text TEXT NOT NULL, text_sha256 TEXT NOT NULL, revision INTEGER NOT NULL, PRIMARY KEY(dossier_id, segment_id))`
	issuesTable                 = `CREATE TABLE IF NOT EXISTS redaction_issues (dossier_id TEXT NOT NULL, issue_id TEXT NOT NULL, segment_id TEXT NOT NULL, rule_code TEXT NOT NULL, severity TEXT NOT NULL, start_offset INTEGER NOT NULL, end_offset INTEGER NOT NULL, reason TEXT NOT NULL, replacement_text TEXT NOT NULL, original_sha256 TEXT NOT NULL, status TEXT NOT NULL, resolved_by TEXT NOT NULL, resolved_at TEXT NOT NULL, PRIMARY KEY(dossier_id, issue_id))`
	confirmationsTable          = `CREATE TABLE IF NOT EXISTS confirmations (dossier_id TEXT NOT NULL, confirmation_id TEXT NOT NULL, decision TEXT NOT NULL, confirmed_by TEXT NOT NULL, confirmed_at TEXT NOT NULL, evidence_digest TEXT NOT NULL, allowed_exceptions BLOB NOT NULL, candidate_sha256 TEXT NOT NULL, note TEXT NOT NULL, PRIMARY KEY(dossier_id, confirmation_id))`
	packagesTable               = `CREATE TABLE IF NOT EXISTS release_packages (dossier_id TEXT PRIMARY KEY, package_id TEXT NOT NULL, manifest_version TEXT NOT NULL, manifest TEXT NOT NULL, redacted_transcript TEXT NOT NULL, consent_snapshot TEXT NOT NULL, reviewer_id TEXT NOT NULL, approved_at TEXT NOT NULL, audit_head_sha256 TEXT NOT NULL, review_snapshot_sha256 TEXT NOT NULL DEFAULT '', content_sha256 TEXT NOT NULL)`
	auditTable                  = `CREATE TABLE IF NOT EXISTS audit_events (dossier_id TEXT NOT NULL, sequence INTEGER NOT NULL, action TEXT NOT NULL, actor_id TEXT NOT NULL, occurred_at TEXT NOT NULL, previous_sha256 TEXT NOT NULL, sha256 TEXT NOT NULL, PRIMARY KEY(dossier_id, sequence))`
	auditDigestIndex            = `CREATE UNIQUE INDEX IF NOT EXISTS audit_digest_idx ON audit_events(dossier_id, sha256)`
	authorizationRevisionsTable = `CREATE TABLE IF NOT EXISTS authorization_revisions (dossier_id TEXT NOT NULL, revision_id TEXT NOT NULL, revision INTEGER NOT NULL, actor_id TEXT NOT NULL, created_at TEXT NOT NULL, payload BLOB NOT NULL, PRIMARY KEY(dossier_id, revision_id))`
	reviewsTable                = `CREATE TABLE IF NOT EXISTS review_snapshots (dossier_id TEXT NOT NULL, review_id TEXT NOT NULL, decision TEXT NOT NULL, reviewer_id TEXT NOT NULL, snapshot_sha256 TEXT NOT NULL, created_at TEXT NOT NULL, payload BLOB NOT NULL, PRIMARY KEY(dossier_id, review_id))`
	remediationRoundsTable      = `CREATE TABLE IF NOT EXISTS remediation_rounds (dossier_id TEXT NOT NULL, round_number INTEGER NOT NULL, started_at TEXT NOT NULL, ended_at TEXT NOT NULL, payload BLOB NOT NULL, PRIMARY KEY(dossier_id, round_number))`
	issueHistoryTable           = `CREATE TABLE IF NOT EXISTS issue_resolution_history (dossier_id TEXT NOT NULL, issue_id TEXT NOT NULL, history_index INTEGER NOT NULL, payload BLOB NOT NULL, PRIMARY KEY(dossier_id, issue_id, history_index))`
)
